spring:
  application:
    name: spring-demo-ai
  datasource:
    url: jdbc:postgresql://localhost:54321/avdocs
    username: admin
    password: secret
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 1536
  docker:
    compose:
      lifecycle-management: START_ONLY
#  main:
#    banner-mode: off
#logging:
#  level:
#    root: off

app:
  docs:
    location: /Users/stefan/sources/spring-ai-avdocs/src/main/resources/docs